apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: backsnap
    app.kubernetes.io/name: namespace
    app.kubernetes.io/instance: backsnap
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: backsnap
    app.kubernetes.io/part-of: backsnap
    app.kubernetes.io/managed-by: kustomize
  name: backsnap
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backsnap-operator
  namespace: backsnap
  labels:
    app: backsnap
    control-plane: controller-manager
    app.kubernetes.io/name: deployment
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: backsnap
    app.kubernetes.io/part-of: backsnap
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      app: backsnap
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        app: backsnap
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - command:
        - /manager
        args:
        # Start a leader election, ensuring that even with two replicas, only one operator
        # is active at a time.
        - --leader-elect
        # In order to include only particular namespaces (default is all namespaces):
        # - --namespaces
        # - one,two,three

        # Alternatively, in order to exclude namespaces. We'd recommend setting a schedule
        # annotation on the namespace instead of using this option, if possible.
        # - --exclude-namespaces
        # - dev,staging,testing

        # Set a default schedule. The default is @daily. We'd recommend keeping this default
        # and overriding it on a per-namespace basis.
        # - --schedule
        # - @weekly

        # Enable manual mode. This never creates automatic PVCBackups, even if a namespace or
        # PVC sets a particular schedule in its annotations. If this is set, the operator only
        # performs back-ups for PVCBackup objects created externally (e.g., by you).
        # - --manual

        # Backsnap automatically creates volume snapshots while it is preparing
        # for a backup. The volume snapshot class name set here is used for all
        # volume snapshots created by Backsnap. Otherwise, the cluster default
        # volume snapshot class name is used.
        # - --snapshotclass
        # - csi-snapshot

        # The storage class name set here is used for all PVCs created by Backsnap
        # both while creating a back-up and while restoring one. Otherwise, the
        # cluster default storage class is used.
        # - -storageclass
        # - csi-block

        # The location and credentials of the S3 bucket where backups will be stored.
        # The S3 hostname can be host, host:port or http://host:port/. Any target supported
        # by Restic is supported, also e.g. MinIO.
        - --s3-host
        - s3.us-west-004.backblazeb2.com
        - --s3-bucket
        - backsnap
        - --s3-access-key-id
        - 004ffef...0003
        - --s3-secret-access-key
        - "K004KC/..."

        # The encryption key by which Restic will client-side encrypt your
        # backup. Do not lose this!
        - --restic-password
        - ChangeMe

        # There are other supported flags, too. See the manager --help (or
        # main.go) for more information.

        image: sjorsgielen/backsnap:latest
        name: manager
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
