# permissions for end users to edit pvcbackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: pvcbackup-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: backsnap
    app.kubernetes.io/part-of: backsnap
    app.kubernetes.io/managed-by: kustomize
  name: pvcbackup-editor-role
rules:
- apiGroups:
  - backsnap.skyb.it
  resources:
  - pvcbackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - backsnap.skyb.it
  resources:
  - pvcbackups/status
  verbs:
  - get
