apiVersion: backsnap.skyb.it/v1alpha1
kind: PVCRestore
metadata:
  name: my-data-restore
  namespace: my-application
spec:
  sourcePvc: "my-data"
  # Empty means 'same namespace as this PVCRestore object'
  sourceNamespace: ""
  # Empty means latest
  sourceSnapshot: ""

  targetPvc: "my-restored-data"
  targetPvcSize: "1Gi"
