name: Run against Minikube
on:
  push:
    branches: '*'
    tags-ignore: '**'
  workflow_call: {}
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'

    - name: go build
      run: |
        make
        if [ "$(git status --porcelain=v1 2>/dev/null | wc -l)" != "0" ]; then
          echo "error: Makefile caused changes"
          git status
          exit 1
        fi

    - name: Start minikube
      uses: medyagh/setup-minikube@latest
      with:
        addons: volumesnapshots,csi-hostpath-driver
    - name: Minikube version
      run: kubectl version
    - name: Run tests
      run:
        make test
